In [1]:
import pandas as pd
import numpy as np
import datetime as dt
from pathlib import Path
import logging
import penaltyblog as pb
from types import SimpleNamespace
import time

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

In [2]:
import sys
sys.path.append('../src')
from dixon_coles import create_team_ratings, simulate_league, process_simulation_results
from scraping_utils import initialize_webdriver, scroll_page, get_results, get_fixtures, get_table

[09/29/26 19:34:56] INFO     No custom team name replacements found. You can configure these in       ]8;id=686899;file:///Users/jaakkotoivonen/repos/soccerdata/soccerdata/_config.py\_config.py]8;;\:]8;id=858263;file:///Users/jaakkotoivonen/repos/soccerdata/soccerdata/_config.py#91\91]8;;\
                             /Users/jaakkotoivonen/soccerdata/config/teamname_replacements.json.

                    INFO     No custom league dict found. You can configure additional leagues in    ]8;id=771802;file:///Users/jaakkotoivonen/repos/soccerdata/soccerdata/_config.py\_config.py]8;;\:]8;id=585809;file:///Users/jaakkotoivonen/repos/soccerdata/soccerdata/_config.py#189\189]8;;\
                             /Users/jaakkotoivonen/soccerdata/config/league_dict.json.

# Functions

In [3]:
def wait_for_results_stable(driver, timeout=60, check_interval=2):
    """Wait until the number of results stops increasing (page fully loaded)"""
    start_time = time.time()
    previous_count = 0
    stable_count = 0
    
    while time.time() - start_time < timeout:
        try:
            current_count = len(driver.find_elements(By.CLASS_NAME, "result"))
            
            if current_count == previous_count:
                stable_count += 1
                if stable_count >= 3:  # Results stable for 3 checks
                    print(f"Results loaded: {current_count} items")
                    return True
            else:
                stable_count = 0
                previous_count = current_count
                print(f"Loading... {current_count} results found")
            
            time.sleep(check_interval)
        except:
            pass
    
    print("Timeout waiting for results to load")
    return False

In [4]:
def get_results_from_single_group(division, season, group):

    driver = initialize_webdriver(f'https://tulospalvelu.palloliitto.fi/category/M{division}!etejp{season}/group/{group}/results')
    scroll_page(driver)
    
    # Wait for results to load
    wait_for_results_stable(driver, timeout=60)
    
    # Get results
    df = get_results(driver)

    return driver, df

In [5]:
def add_metadata(df, division, season, group):
    df['league_division'] = division
    df['season'] = season
    df['group'] = group
    return df

In [6]:
def fetch_season_data(division, season):

    all_dfs = []
    my_group = 1

    while True:
        print(f"Scraping group {my_group}...")
        
        driver, df = get_results_from_single_group(division, season, my_group)
        
        # Check if we got any results
        if df is None or len(df) == 0:
            print(f"No results found for group {my_group}. Stopping.")
            driver.quit()
            break
        
        print(f"Group {my_group}: Found {len(df)} results")
        
        # Add metadata
        df = add_metadata(df, division, season, my_group)
        
        all_dfs.append(df)
        
        # Close driver and move to next group
        driver.quit()
        my_group += 1

    # Combine all results
    if all_dfs:
        combined_df = pd.concat(all_dfs, ignore_index=True)
        print(f"\nTotal results scraped: {len(combined_df)}")
        combined_df
    else:
        print("No results were scraped")
    
    return combined_df

# Fetch leagues group-by-group

## 2026

In [7]:
results_df = fetch_season_data(5, 26)
display(results_df.head())
display(results_df.tail())
display(results_df.shape)

Scraping group 1...
Loading... 144 results found
Results loaded: 144 items
Group 1: Found 71 results
Scraping group 2...
Loading... 100 results found
Results loaded: 100 items
Group 2: Found 49 results
Scraping group 3...
Loading... 100 results found
Results loaded: 100 items
Group 3: Found 50 results
Scraping group 4...
Loading... 100 results found
Results loaded: 100 items
Group 4: Found 50 results
Scraping group 5...
Loading... 144 results found
Results loaded: 144 items
Group 5: Found 71 results
Scraping group 6...
Loading... 100 results found
Results loaded: 100 items
Group 6: Found 49 results
Scraping group 7...
Loading... 180 results found
Results loaded: 180 items
Group 7: Found 89 results
Scraping group 8...
Loading... 100 results found
Results loaded: 100 items
Group 8: Found 48 results
Scraping group 9...
Results loaded: 0 items
No results found for group 9. Stopping.

Total results scraped: 477

  team_home  team_away goals_home goals_away  league_division  season  group
0   Tikka/2   FC Samba          7          3                5      26      1
1       PEF  HooGee/23          4          0                5      26      1
2    LoPa/2      EPS/2          0          1                5      26      1
3   GrIFK/2       KaPy          4          2                5      26      1
4    LoPa/2        PEF          2          3                5      26      1

,team_home,team_away,goals_home,goals_away,league_division,season,group
472,Union Plaani/17,Flamingo United,1,2,5,26,8
473,KyPa,FC Lahti/3,7,0,5,26,8
474,Union Plaani/17,PaPe,3,2,5,26,8
475,Korian Klubi,KarPo,5,4,5,26,8
476,FC Loviisa,Nopsa,6,2,5,26,8

(477, 7)

In [8]:
results_df_aux = fetch_season_data(6, 26)
results_df = pd.concat([results_df, results_df_aux], ignore_index=True)
display(results_df_aux.head())
display(results_df_aux.tail())
display(results_df_aux.shape)

Scraping group 1...
Loading... 142 results found
Results loaded: 142 items
Group 1: Found 70 results
Scraping group 2...
Loading... 144 results found
Results loaded: 144 items
Group 2: Found 71 results
Scraping group 3...
Results loaded: 0 items
No results found for group 3. Stopping.

Total results scraped: 141

,team_home,team_away,goals_home,goals_away,league_division,season,group
0,Olympique Club Espoo,FC Kirkkonummi/2,10,4,6,26,1
1,Länsiväylän Dynamo,EsPa/Keltavihree 2,1,3,6,26,1
2,HooGee/Hodari,LoPa/Internationales,1,1,6,26,1
3,EPS/3,Hukat,3,2,6,26,1
4,EPS/3,HooGee/Hodari,6,1,6,26,1

,team_home,team_away,goals_home,goals_away,league_division,season,group
136,LePa/Cityboys,Espoon Sonnit,1,1,6,26,2
137,Geishan Pallo,Vermo Vikings,1,3,6,26,2
138,Vermo Vikings,Kilo IF/3,7,3,6,26,2
139,PPV/Seos,PEP/Pitkätossut,1,3,6,26,2
140,Espoon Sonnit,PiTa/II,1,0,6,26,2

(141, 7)

In [9]:
my_division = 6
my_season = 26
my_group = 14
driver, df = get_results_from_single_group(my_division, my_season, my_group)
df = add_metadata(df, my_division, my_season, my_group)
driver.quit()
results_df = pd.concat([results_df, df], ignore_index=True)
results_df

Loading... 200 results found
Results loaded: 200 items

,team_home,team_away,goals_home,goals_away,league_division,season,group
0,Tikka/2,FC Samba,7,3,5,26,1
1,PEF,HooGee/23,4,0,5,26,1
2,LoPa/2,EPS/2,0,1,5,26,1
3,GrIFK/2,KaPy,4,2,5,26,1
4,LoPa/2,PEF,2,3,5,26,1
...,...,...,...,...,...,...,...
713,FC POHU/Traktori,Helsinki United,8,1,6,26,14
714,FC Juvantus,HJK/Sininen,4,0,6,26,14
715,FC POHU/Futboleros,Töölö Tigers,0,11,6,26,14
716,HJK/Töölön Ihme,HH Palloveikot,1,4,6,26,14
717,HP-47 Helsinki,FC Jaliskirahvit,0,2,6,26,14

In [10]:
my_division = 6
my_season = 26
my_group = 5
driver, df = get_results_from_single_group(my_division, my_season, my_group)
df = add_metadata(df, my_division, my_season, my_group)
driver.quit()
results_df = pd.concat([results_df, df], ignore_index=True)
results_df

Loading... 144 results found
Results loaded: 144 items

,team_home,team_away,goals_home,goals_away,league_division,season,group
0,Tikka/2,FC Samba,7,3,5,26,1
1,PEF,HooGee/23,4,0,5,26,1
2,LoPa/2,EPS/2,0,1,5,26,1
3,GrIFK/2,KaPy,4,2,5,26,1
4,LoPa/2,PEF,2,3,5,26,1
...,...,...,...,...,...,...,...
785,Helsingin Pallo-Veikot,FC Babylon,0,1,6,26,5
786,Ponnistus/Peruskallio,Lännen Torpedo,0,7,6,26,5
787,KPPK,Himalayan Sports Club,3,3,6,26,5
788,FC OHO UNITED,Helsingin Pallo-Veikot,1,2,6,26,5
789,FC Babylon,HJK/Kantsu 94,2,1,6,26,5

In [11]:
my_division = 6
my_season = 26
my_group = 6
driver, df = get_results_from_single_group(my_division, my_season, my_group)
df = add_metadata(df, my_division, my_season, my_group)
driver.quit()
results_df = pd.concat([results_df, df], ignore_index=True)
results_df

Loading... 144 results found
Results loaded: 144 items

,team_home,team_away,goals_home,goals_away,league_division,season,group
0,Tikka/2,FC Samba,7,3,5,26,1
1,PEF,HooGee/23,4,0,5,26,1
2,LoPa/2,EPS/2,0,1,5,26,1
3,GrIFK/2,KaPy,4,2,5,26,1
4,LoPa/2,PEF,2,3,5,26,1
...,...,...,...,...,...,...,...
855,HeMan,Kullervo/Mosaic,1,5,6,26,6
856,Kullervo/Mosaic,FC Kevyt Olo,6,0,6,26,6
857,HeMan,Kurvin Vauhti/Partiz,2,2,6,26,6
858,Käpylä Maanantai,FC Kiffen/2,0,1,6,26,6
859,FC Germania/Akademie,SAPA/2,0,1,6,26,6

In [12]:
my_division = 6
my_season = 26
my_group = 7
driver, df = get_results_from_single_group(my_division, my_season, my_group)
df = add_metadata(df, my_division, my_season, my_group)
driver.quit()
results_df = pd.concat([results_df, df], ignore_index=True)
results_df

Loading... 144 results found
Results loaded: 144 items

,team_home,team_away,goals_home,goals_away,league_division,season,group
0,Tikka/2,FC Samba,7,3,5,26,1
1,PEF,HooGee/23,4,0,5,26,1
2,LoPa/2,EPS/2,0,1,5,26,1
3,GrIFK/2,KaPy,4,2,5,26,1
4,LoPa/2,PEF,2,3,5,26,1
...,...,...,...,...,...,...,...
926,HePuLi,MLHF/Reserves,3,0,6,26,7
927,IF Gnistan/Fenix,KasiNolla,2,5,6,26,7
928,Sammuneet Tähdet,HePuLi,2,1,6,26,7
929,MLHF/Reserves,Jokerit FC/2,3,0,6,26,7
930,AC StaSi,FC Degis,0,3,6,26,7

In [13]:
my_division = 6
my_season = 26
my_group = 8
driver, df = get_results_from_single_group(my_division, my_season, my_group)
df = add_metadata(df, my_division, my_season, my_group)
driver.quit()
results_df = pd.concat([results_df, df], ignore_index=True)
results_df

Loading... 122 results found
Results loaded: 122 items

,team_home,team_away,goals_home,goals_away,league_division,season,group
0,Tikka/2,FC Samba,7,3,5,26,1
1,PEF,HooGee/23,4,0,5,26,1
2,LoPa/2,EPS/2,0,1,5,26,1
3,GrIFK/2,KaPy,4,2,5,26,1
4,LoPa/2,PEF,2,3,5,26,1
...,...,...,...,...,...,...,...
980,Trikiinit,Ariana FC,6,2,6,26,8
981,MK United/Warriors,Ruila,11,5,6,26,8
982,Ruila,Scorpions,2,5,6,26,8
983,PK-35/Legendat,MK United/Warriors,2,6,6,26,8
984,FC Viikingit/S.C.P L,VAMOL/Myyrmäki,0,2,6,26,8

In [14]:
my_division = 6
my_season = 26
my_group = 9
driver, df = get_results_from_single_group(my_division, my_season, my_group)
df = add_metadata(df, my_division, my_season, my_group)
driver.quit()
results_df = pd.concat([results_df, df], ignore_index=True)
results_df

Loading... 92 results found
Results loaded: 92 items

,team_home,team_away,goals_home,goals_away,league_division,season,group
0,Tikka/2,FC Samba,7,3,5,26,1
1,PEF,HooGee/23,4,0,5,26,1
2,LoPa/2,EPS/2,0,1,5,26,1
3,GrIFK/2,KaPy,4,2,5,26,1
4,LoPa/2,PEF,2,3,5,26,1
...,...,...,...,...,...,...,...
1022,KeiKa/United,NJS/Jucola,2,1,6,26,9
1023,KoiPS/Dynamo,KeiKa/United,2,1,6,26,9
1024,FC Tuusula,Afro Foot Club/2,0,2,6,26,9
1025,NJS/Jucola,PPS/OS,1,1,6,26,9
1026,FC Tuusula,KoiPS/Dynamo,2,3,6,26,9

In [15]:
my_division = 6
my_season = 26
my_group = 10
driver, df = get_results_from_single_group(my_division, my_season, my_group)
df = add_metadata(df, my_division, my_season, my_group)
driver.quit()
results_df = pd.concat([results_df, df], ignore_index=True)
results_df

Loading... 164 results found
Results loaded: 164 items

,team_home,team_away,goals_home,goals_away,league_division,season,group
0,Tikka/2,FC Samba,7,3,5,26,1
1,PEF,HooGee/23,4,0,5,26,1
2,LoPa/2,EPS/2,0,1,5,26,1
3,GrIFK/2,KaPy,4,2,5,26,1
4,LoPa/2,PEF,2,3,5,26,1
...,...,...,...,...,...,...,...
1092,RistiFemma,Pelikaani,2,3,6,26,10
1093,FC Kulmakikka,JäPS/Akatemia 2,3,1,6,26,10
1094,Ares -86,FC MVP,1,1,6,26,10
1095,Mäntsälän Urheilijat,HAlku/FC,3,0,6,26,10
1096,AC JazzPa,RistiFemma,1,4,6,26,10

In [16]:
my_division = 6
my_season = 26
my_group = 11
driver, df = get_results_from_single_group(my_division, my_season, my_group)
df = add_metadata(df, my_division, my_season, my_group)
driver.quit()
results_df = pd.concat([results_df, df], ignore_index=True)
results_df

Results loaded: 0 items

,team_home,team_away,goals_home,goals_away,league_division,season,group
0,Tikka/2,FC Samba,7,3,5,26,1
1,PEF,HooGee/23,4,0,5,26,1
2,LoPa/2,EPS/2,0,1,5,26,1
3,GrIFK/2,KaPy,4,2,5,26,1
4,LoPa/2,PEF,2,3,5,26,1
...,...,...,...,...,...,...,...
1092,RistiFemma,Pelikaani,2,3,6,26,10
1093,FC Kulmakikka,JäPS/Akatemia 2,3,1,6,26,10
1094,Ares -86,FC MVP,1,1,6,26,10
1095,Mäntsälän Urheilijat,HAlku/FC,3,0,6,26,10
1096,AC JazzPa,RistiFemma,1,4,6,26,10

In [17]:
my_division = 6
my_season = 26
my_group = 12
driver, df = get_results_from_single_group(my_division, my_season, my_group)
df = add_metadata(df, my_division, my_season, my_group)
driver.quit()
results_df = pd.concat([results_df, df], ignore_index=True)
results_df

Loading... 200 results found
Results loaded: 200 items

,team_home,team_away,goals_home,goals_away,league_division,season,group
0,Tikka/2,FC Samba,7,3,5,26,1
1,PEF,HooGee/23,4,0,5,26,1
2,LoPa/2,EPS/2,0,1,5,26,1
3,GrIFK/2,KaPy,4,2,5,26,1
4,LoPa/2,PEF,2,3,5,26,1
...,...,...,...,...,...,...,...
1189,ViSa,Jäntevä/Ukot,1,1,6,26,12
1190,MyPa/FC,FC Villisiat,3,0,6,26,12
1191,Lahden United,PoPo,1,1,6,26,12
1192,Iitin Pallo-68,ViSa,4,1,6,26,12
1193,FC Villisiat,Korian Klubi/2,5,1,6,26,12

In [18]:
results_df_aux = fetch_season_data(7, 26)
results_df = pd.concat([results_df, results_df_aux], ignore_index=True)
display(results_df_aux.head())
display(results_df_aux.tail())
display(results_df_aux.shape)

Scraping group 1...
Loading... 56 results found
Results loaded: 56 items
Group 1: Found 28 results
Scraping group 2...
Loading... 56 results found
Results loaded: 56 items
Group 2: Found 28 results
Scraping group 3...
Loading... 56 results found
Results loaded: 56 items
Group 3: Found 28 results
Scraping group 4...
Loading... 48 results found
Results loaded: 48 items
Group 4: Found 23 results
Scraping group 5...
Loading... 46 results found
Results loaded: 46 items
Group 5: Found 23 results
Scraping group 6...
Loading... 46 results found
Results loaded: 46 items
Group 6: Found 23 results
Scraping group 7...
Loading... 48 results found
Results loaded: 48 items
Group 7: Found 24 results
Scraping group 8...
Results loaded: 0 items
No results found for group 8. Stopping.

Total results scraped: 177

,team_home,team_away,goals_home,goals_away,league_division,season,group
0,Kilo IF/2,Tavastia/FC Mojo,0,4,7,26,1
1,MoPo,Cosmos,2,0,7,26,1
2,Kasiysi/3,PPJ/Faijat,1,3,7,26,1
3,FC POHU/Kova Kamppi,OT-77,0,1,7,26,1
4,OT-77,Kasiysi/3,3,1,7,26,1

,team_home,team_away,goals_home,goals_away,league_division,season,group
172,ToTe/Arabia,Kilo IF/2,1,3,7,26,7
173,PiTa/III,FC Pakila,1,3,7,26,7
174,Kasiysi/3,PiTa/III,0,2,7,26,7
175,JJ Vepo,ToTe/Arabia,0,1,7,26,7
176,Kilo IF/2,Käpylän Sekunda,1,0,7,26,7

(177, 7)

In [ ]:
#results_df.to_csv('../data/finland_5_6_7_divisions_results_26.csv', index=False)

## 6th division

In [ ]:
results_df = fetch_season_data(6, 25)
display(results_df.head())
display(results_df.tail())
display(results_df.shape)

In [ ]:
# drop promotion playoff games

results_df = results_df[~(
    (results_df['season'] == 25) & 
    (results_df['league_division'] == 6) & 
    (results_df['group'] == 12)
)]

display(results_df.shape)

In [ ]:
results_df_aux = fetch_season_data(6, 24)
results_df = pd.concat([results_df, results_df_aux], ignore_index=True)
display(results_df_aux.head())
display(results_df_aux.tail())
display(results_df_aux.shape)

In [ ]:
# drop promotion playoff games

results_df = results_df[~(
    (results_df['season'] == 24) & 
    (results_df['league_division'] == 6) & 
    (results_df['group'] == 11)
)]

display(results_df.shape)

In [ ]:
results_df_aux = fetch_season_data(6, 23)
results_df = pd.concat([results_df, results_df_aux], ignore_index=True)
display(results_df_aux.head())
display(results_df_aux.tail())
display(results_df_aux.shape)

In [ ]:
# drop promotion playoff games

results_df = results_df[~(
    (results_df['season'] == 23) & 
    (results_df['league_division'] == 6) & 
    (results_df['group'] == 11)
)]

display(results_df.shape)

In [ ]:
results_df_aux = fetch_season_data(6, 22)
results_df = pd.concat([results_df, results_df_aux], ignore_index=True)
display(results_df_aux.head())
display(results_df_aux.tail())
display(results_df_aux.shape)

In [ ]:
results_df_aux = fetch_season_data(6, 21)
results_df = pd.concat([results_df, results_df_aux], ignore_index=True)
display(results_df_aux.head())
display(results_df_aux.tail())
display(results_df_aux.shape)

In [ ]:
results_df_aux = fetch_season_data(6, 20)
results_df = pd.concat([results_df, results_df_aux], ignore_index=True)
display(results_df_aux.head())
display(results_df_aux.tail())
display(results_df_aux.shape)

In [ ]:
my_division = 6
my_season = 20
my_group = 4
driver, df = get_results_from_single_group(my_division, my_season, my_group)
df = add_metadata(df, my_division, my_season, my_group)
driver.quit()
results_df = pd.concat([results_df, df], ignore_index=True)
results_df

In [ ]:
my_division = 6
my_season = 20
my_group = 7
driver, df = get_results_from_single_group(my_division, my_season, my_group)
df = add_metadata(df, my_division, my_season, my_group)
driver.quit()
results_df = pd.concat([results_df, df], ignore_index=True)
results_df

In [ ]:
my_division = 6
my_season = 20
my_group = 11
driver, df = get_results_from_single_group(my_division, my_season, my_group)
df = add_metadata(df, my_division, my_season, my_group)
driver.quit()
results_df = pd.concat([results_df, df], ignore_index=True)
results_df

In [ ]:
my_division = 6
my_season = 20
my_group = 9
driver, df = get_results_from_single_group(my_division, my_season, my_group)
df = add_metadata(df, my_division, my_season, my_group)
driver.quit()
results_df = pd.concat([results_df, df], ignore_index=True)
results_df

In [ ]:
my_division = 6
my_season = 20
my_group = 10
driver, df = get_results_from_single_group(my_division, my_season, my_group)
df = add_metadata(df, my_division, my_season, my_group)
driver.quit()
results_df = pd.concat([results_df, df], ignore_index=True)
results_df

In [ ]:
#results_df.to_csv('../data/6th_division_results_20-25.csv', index=False)

## 5th division

In [ ]:
results_df = fetch_season_data(5, 25)
display(results_df.head())
display(results_df.tail())
display(results_df.shape)

In [ ]:
# drop promotion playoff games

results_df = results_df[~(
    (results_df['season'] == 25) & 
    (results_df['league_division'] == 5) & 
    (results_df['group'] == 9)
)]

display(results_df.shape)

In [ ]:
results_df_aux = fetch_season_data(5, 24)
results_df = pd.concat([results_df, results_df_aux], ignore_index=True)
display(results_df_aux.head())
display(results_df_aux.tail())
display(results_df_aux.shape)

In [ ]:
# drop promotion playoff games

results_df = results_df[~(
    (results_df['season'] == 24) & 
    (results_df['league_division'] == 5) & 
    (results_df['group'] == 9)
)]

display(results_df.shape)

In [ ]:
results_df_aux = fetch_season_data(5, 23)
results_df = pd.concat([results_df, results_df_aux], ignore_index=True)
display(results_df_aux.head())
display(results_df_aux.tail())
display(results_df_aux.shape)

In [ ]:
# drop promotion playoff games

results_df = results_df[~(
    (results_df['season'] == 23) & 
    (results_df['league_division'] == 5) & 
    (results_df['group'] == 9)
)]

display(results_df.shape)

In [ ]:
results_df_aux = fetch_season_data(5, 22)
results_df = pd.concat([results_df, results_df_aux], ignore_index=True)
display(results_df_aux.head())
display(results_df_aux.tail())
display(results_df_aux.shape)

In [ ]:
# drop promotion playoff games

results_df = results_df[~(
    (results_df['season'] == 22) & 
    (results_df['league_division'] == 5) & 
    (results_df['group'] == 9)
)]

display(results_df.shape)

In [ ]:
results_df_aux = fetch_season_data(5, 21)
results_df = pd.concat([results_df, results_df_aux], ignore_index=True)
display(results_df_aux.head())
display(results_df_aux.tail())
display(results_df_aux.shape)

In [ ]:
results_df.groupby(['season', 'league_division', 'group']).size()

In [ ]:
# drop promotion playoff games

results_df = results_df[~(
    (results_df['season'] == 21) & 
    (results_df['league_division'] == 5) & 
    (results_df['group'] >= 9)
)]

display(results_df.shape)

In [ ]:
my_division = 5
my_season = 20
my_group = 11
driver, df = get_results_from_single_group(my_division, my_season, my_group)
df = add_metadata(df, my_division, my_season, my_group)
driver.quit()
results_df = pd.concat([results_df, df], ignore_index=True)
results_df

In [ ]:
my_division = 5
my_season = 20
my_group = 12
driver, df = get_results_from_single_group(my_division, my_season, my_group)
df = add_metadata(df, my_division, my_season, my_group)
driver.quit()
results_df = pd.concat([results_df, df], ignore_index=True)
results_df

In [ ]:
my_division = 5
my_season = 20
my_group = 13
driver, df = get_results_from_single_group(my_division, my_season, my_group)
df = add_metadata(df, my_division, my_season, my_group)
driver.quit()
results_df = pd.concat([results_df, df], ignore_index=True)
results_df

In [ ]:
my_division = 5
my_season = 20
my_group = 14
driver, df = get_results_from_single_group(my_division, my_season, my_group)
df = add_metadata(df, my_division, my_season, my_group)
driver.quit()
results_df = pd.concat([results_df, df], ignore_index=True)
results_df

In [ ]:
my_division = 5
my_season = 20
my_group = 15
driver, df = get_results_from_single_group(my_division, my_season, my_group)
df = add_metadata(df, my_division, my_season, my_group)
driver.quit()
results_df = pd.concat([results_df, df], ignore_index=True)
results_df

In [ ]:
my_division = 5
my_season = 20
my_group = 16
driver, df = get_results_from_single_group(my_division, my_season, my_group)
df = add_metadata(df, my_division, my_season, my_group)
driver.quit()
results_df = pd.concat([results_df, df], ignore_index=True)
results_df

In [ ]:
#results_df.to_csv('../data/5th_division_results_20-25.csv', index=False)

## 7th division - season 2020

In [ ]:
results_df = fetch_season_data(7, 25)
display(results_df.head())
display(results_df.tail())
display(results_df.shape)

In [ ]:
results_df_aux = fetch_season_data(7, 24)
results_df = pd.concat([results_df, results_df_aux], ignore_index=True)
display(results_df_aux.head())
display(results_df_aux.tail())
display(results_df_aux.shape)

In [ ]:
results_df_aux = fetch_season_data(7, 23)
results_df = pd.concat([results_df, results_df_aux], ignore_index=True)
display(results_df_aux.head())
display(results_df_aux.tail())
display(results_df_aux.shape)

In [ ]:
my_division = 7
my_season = 22
my_group = 3
driver, df = get_results_from_single_group(my_division, my_season, my_group)
df = add_metadata(df, my_division, my_season, my_group)
driver.quit()
results_df = pd.concat([results_df, df], ignore_index=True)
results_df

In [ ]:
my_division = 7
my_season = 22
my_group = 4
driver, df = get_results_from_single_group(my_division, my_season, my_group)
df = add_metadata(df, my_division, my_season, my_group)
driver.quit()
results_df = pd.concat([results_df, df], ignore_index=True)
results_df

In [ ]:
my_division = 7
my_season = 22
my_group = 5
driver, df = get_results_from_single_group(my_division, my_season, my_group)
df = add_metadata(df, my_division, my_season, my_group)
driver.quit()
results_df = pd.concat([results_df, df], ignore_index=True)
results_df

In [ ]:
my_division = 7
my_season = 22
my_group = 6
driver, df = get_results_from_single_group(my_division, my_season, my_group)
df = add_metadata(df, my_division, my_season, my_group)
driver.quit()
results_df = pd.concat([results_df, df], ignore_index=True)
results_df

In [ ]:
my_division = 7
my_season = 22
my_group = 8
driver, df = get_results_from_single_group(my_division, my_season, my_group)
df = add_metadata(df, my_division, my_season, my_group)
driver.quit()
results_df = pd.concat([results_df, df], ignore_index=True)
results_df

In [ ]:
my_division = 7
my_season = 22
my_group = 9
driver, df = get_results_from_single_group(my_division, my_season, my_group)
df = add_metadata(df, my_division, my_season, my_group)
driver.quit()
results_df = pd.concat([results_df, df], ignore_index=True)
results_df

In [ ]:
results_df_aux = fetch_season_data(7, 21)
results_df = pd.concat([results_df, results_df_aux], ignore_index=True)
display(results_df_aux.head())
display(results_df_aux.tail())
display(results_df_aux.shape)

In [ ]:
my_division = 7
my_season = 20
my_group = 4
driver, df = get_results_from_single_group(my_division, my_season, my_group)
df = add_metadata(df, my_division, my_season, my_group)
driver.quit()
results_df = pd.concat([results_df, df], ignore_index=True)
results_df

In [ ]:
my_division = 7
my_season = 20
my_group = 5
driver, df = get_results_from_single_group(my_division, my_season, my_group)
df = add_metadata(df, my_division, my_season, my_group)
driver.quit()
results_df = pd.concat([results_df, df], ignore_index=True)
results_df

In [ ]:
results_df.to_csv('../data/7th_division_results_20-25.csv', index=False)

# Fetch full leagues (obsolete)

## Fetch data

In [ ]:
driver = initialize_webdriver(f'https://tulospalvelu.palloliitto.fi/category/M7!etejp25/results') # all results
scroll_page(driver)

In [ ]:
df = get_results(driver)
df['season'] = '2025'
df['league_division'] = '7'
df

In [ ]:
driver = initialize_webdriver(f'https://tulospalvelu.palloliitto.fi/category/M7!etejp24/results') # all results
scroll_page(driver)

In [ ]:
aux = get_results(driver)
aux['season'] = '2024'
aux['league_division'] = '7'
aux

In [ ]:
df = pd.concat([df, aux], ignore_index=True)
df

In [ ]:
driver = initialize_webdriver(f'https://tulospalvelu.palloliitto.fi/category/M7!etejp23/results') # all results
scroll_page(driver)

In [ ]:
aux = get_results(driver)
aux['season'] = '2023'
aux['league_division'] = '7'
aux

In [ ]:
df = pd.concat([df, aux], ignore_index=True)
df

In [ ]:
driver = initialize_webdriver(f'https://tulospalvelu.palloliitto.fi/category/M6!etejp25/results') # all results
scroll_page(driver)

In [ ]:
aux = get_results(driver)
aux['season'] = '2025'
aux['league_division'] = '6'
aux

In [ ]:
df = pd.concat([df, aux], ignore_index=True)
df

In [ ]:
driver = initialize_webdriver(f'https://tulospalvelu.palloliitto.fi/category/M6!etejp24/results') # all results
scroll_page(driver)

In [ ]:
aux = get_results(driver)
aux['season'] = '2024'
aux['league_division'] = '6'
aux

In [ ]:
df = pd.concat([df, aux], ignore_index=True)
df

In [ ]:
driver = initialize_webdriver(f'https://tulospalvelu.palloliitto.fi/category/M6!etejp23/results') # all results
scroll_page(driver)

In [ ]:
aux = get_results(driver)
aux['season'] = '2023'
aux['league_division'] = '6'
aux

In [ ]:
df = pd.concat([df, aux], ignore_index=True)
df

In [ ]:
df.to_csv('../data/results/finland_6_7_divisions_results_2023_2025.csv', index=False)

## Fetch more data

In [ ]:
df = pd.read_csv('../data/results/finland_6_7_divisions_results_2023_2025.csv')
display(df.head())
display(df.tail())
display(df.shape)

In [ ]:
driver = initialize_webdriver(f'https://tulospalvelu.palloliitto.fi/category/M7!etejp22/results') # all results
scroll_page(driver)

In [ ]:
aux = get_results(driver)
aux['season'] = '2022'
aux['league_division'] = '7'
aux

In [ ]:
df = pd.concat([df, aux], ignore_index=True)
df

In [ ]:
driver = initialize_webdriver(f'https://tulospalvelu.palloliitto.fi/category/M7!etejp21/results') # all results
scroll_page(driver)

In [ ]:
aux = get_results(driver)
aux['season'] = '2021'
aux['league_division'] = '7'
aux

In [ ]:
df = pd.concat([df, aux], ignore_index=True)
df

In [ ]:
driver = initialize_webdriver(f'https://tulospalvelu.palloliitto.fi/category/M7!etejp20/results') # all results
scroll_page(driver)

In [ ]:
aux = get_results(driver)
aux['season'] = '2020'
aux['league_division'] = '7'
aux

In [ ]:
df = pd.concat([df, aux], ignore_index=True)
df

In [ ]:
driver = initialize_webdriver(f'https://tulospalvelu.palloliitto.fi/category/M6!etejp22/results') # all results
scroll_page(driver)

In [ ]:
aux = get_results(driver)
aux['season'] = '2022'
aux['league_division'] = '6'
aux

In [ ]:
df = pd.concat([df, aux], ignore_index=True)
df

In [ ]:
driver = initialize_webdriver(f'https://tulospalvelu.palloliitto.fi/category/M6!etejp21/results') # all results
scroll_page(driver)

In [ ]:
aux = get_results(driver)
aux['season'] = '2021'
aux['league_division'] = '6'
aux

In [ ]:
df = pd.concat([df, aux], ignore_index=True)
df

In [ ]:
driver = initialize_webdriver(f'https://tulospalvelu.palloliitto.fi/category/M6!etejp20/results') # all results
scroll_page(driver)

In [ ]:
aux = get_results(driver)
aux['season'] = '2020'
aux['league_division'] = '6'
aux

In [ ]:
df = pd.concat([df, aux], ignore_index=True)
df

In [ ]:
df.to_csv('../data/results/finland_6_7_divisions.csv', index=False)

# Data processing

In [ ]:
df_5div = pd.read_csv('../data/5th_division_results_20-25.csv')
display(df_5div.head())
display(df_5div.shape)

In [ ]:
df_6div = pd.read_csv('../data/6th_division_results_20-25.csv')
display(df_6div.head())
display(df_6div.shape)

In [ ]:
df_7div = pd.read_csv('../data/7th_division_results_20-25.csv')
display(df_7div.head())
display(df_7div.shape)

In [ ]:
#df_6_7_div = pd.read_csv('../data/results/finland_6_7_divisions.csv')
#season_mapping = {2025: 25, 2024: 24, 2023: 23, 2022: 22, 2021: 21, 2020: 20}
#df_6_7_div['season'] = df_6_7_div['season'].map(season_mapping)
#display(df_6_7_div.head())
#display(df_6_7_div.shape)

In [ ]:
#df_7div_20 = pd.read_csv('../data/7th_division_results_20.csv')
#display(df_7div_20.head())
#display(df_7div_20.shape)

In [ ]:
# df_7div = df_6_7_div[df_6_7_div['league_division'] == 7].copy()
# df_7div = df_7div[~((df_7div['season'] == 2020))]
# df_7div = pd.concat([df_7div, df_7div_20], ignore_index=True)
# df_7div.loc[df_7div.group.isnull(), 'group'] = 1
# df_7div

In [ ]:
df = pd.concat([df_5div, df_6div, df_7div], ignore_index=True)
df

In [ ]:
df.groupby(['season', 'league_division', 'group']).size().plot(kind='bar', figsize=(12,6), title='Number of matches per season/division/group');

In [ ]:
with pd.option_context('display.max_rows', None):
    display(df.groupby(['season', 'league_division', 'group']).size())

In [ ]:
df.info()

In [ ]:
# fix dtypes
#df[['goals_home', 'goals_away', 'season', 'league_division']] = df[['goals_home', 'goals_away', 'season', 'league_division']].astype(int)

In [ ]:
team_name = 'Trikiinit'
with pd.option_context('display.max_rows', None):
    display(df[(df['team_home']==team_name) | (df['team_away']==team_name)])

In [ ]:
# Group by "team_home" and calculate the set of league_division values
team_divisions = df.groupby("team_home")["league_division"].apply(set)

# Filter teams where the number of unique league_division values is greater than 1
teams_with_multiple_divisions = team_divisions[team_divisions.apply(len) > 1]

# Get the team names
teams = teams_with_multiple_divisions.index.tolist()

print("Teams that have played in more than one division:")
print(teams)

In [ ]:
print('Number of teams in total:')
print(df['team_home'].nunique())

In [ ]:
team_name = 'Trikiinit'
df[(df['team_home']==team_name) | (df['team_away']==team_name)].groupby(['season'])['league_division'].unique().reset_index().sort_values(by='season')

In [ ]:
#df.to_csv('../data/finland_5_6_7_divisions_results_20-25.csv', index=False)