In [1]:
import soccerdata as sd
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

[09/20/26 13:06:02] INFO     No custom team name replacements found. You can configure these in       ]8;id=152121;file:///Users/jaakkotoivonen/repos/soccerdata/soccerdata/_config.py\_config.py]8;;\:]8;id=530982;file:///Users/jaakkotoivonen/repos/soccerdata/soccerdata/_config.py#91\91]8;;\
                             /Users/jaakkotoivonen/soccerdata/config/teamname_replacements.json.

                    INFO     No custom league dict found. You can configure additional leagues in    ]8;id=938991;file:///Users/jaakkotoivonen/repos/soccerdata/soccerdata/_config.py\_config.py]8;;\:]8;id=504648;file:///Users/jaakkotoivonen/repos/soccerdata/soccerdata/_config.py#189\189]8;;\
                             /Users/jaakkotoivonen/soccerdata/config/league_dict.json.

In [ ]:
league_name="ENG-Premier League" 
previous_season='2025'
current_season='2026'
fbref = sd.FBref(leagues=league_name, seasons=[previous_season, current_season])

In [ ]:
fbref_fixtures = fbref.read_schedule()
fbref_fixtures

In [ ]:
matches = fbref_fixtures
fixtures = matches[matches.score.isnull()].copy()
fixtures

In [ ]:
fbref.read_league_table()

In [ ]:
league_name="Big 5 European Leagues Combined" 
current_season='2025'
fbref = sd.FBref(leagues=league_name, seasons=[current_season])

In [ ]:
standard = fbref.read_player_season_stats(stat_type="standard")
standard.head()

In [ ]:
standard.reset_index()['player']

In [ ]:
passing = fbref.read_player_season_stats(stat_type="passing")
passing.head()

In [ ]:
passing[('KP')]

In [ ]:
defense = fbref.read_player_season_stats(stat_type="defense")
defense.head()

In [ ]:
df = pd.merge(standard, passing, left_index=True, right_index=True, suffixes=('_standard', '_passing'), how='inner')
display(df.head())
display(df.shape)

In [ ]:
df[df['pos_standard'].str.contains('DF')]

In [ ]:
team_standard = fbref.read_team_season_stats(stat_type="standard")
team_standard.head()

In [ ]:
team_standard.reset_index()[[('team'), ('Poss')]]

In [ ]:
match_stats = fbref.read_player_match_stats(stat_type="summary", match_id='e730a21b')
match_stats

## Fotmob

In [2]:
fotmob = sd.FotMob(leagues=league_name, seasons=current_season)
league_table = fotmob.read_league_table().reset_index(drop=True)
league_table

AttributeError: module 'soccerdata' has no attribute 'FotMob'

In [ ]:
teams = np.sort(league_table['team'].unique())
teams

In [ ]:
np.sort(fixtures['home_team'].unique())

In [ ]:
fotmob = sd.FotMob(leagues=league_name, seasons=[previous_season, current_season])
matches = fotmob.read_schedule()

In [ ]:
matches

In [ ]:
matches = matches[matches.home_score.notnull()]
matches

In [ ]:
matches = matches.rename(
         columns={'home_score':'xG_home', 'away_score':'xG_away', 'home_team':'Home', 'away_team':'Away'}
         )
matches

In [ ]:
matches.dtypes

In [ ]:
print(matches['date'].dt.tz)

In [ ]:
import datetime as dt
import pytz
current_date = dt.datetime.now(pytz.UTC)
current_date

In [ ]:
matches['date'].apply(lambda x: (current_date - x).days)

In [ ]:
fixtures

In [ ]:
league_table = (fotmob.read_league_table()
            .rename(columns={'team': 'Squad'})
            .reset_index(drop=True)
        )
league_table['Rk'] = league_table.index + 1
league
league_table

In [ ]:
league_table.dtypes

In [ ]:
league_table.loc[0,'GF']

In [ ]:
sorted_matrix = pd.read_csv('../output/league_matrices/25-11-09_15-13-48--ENG-Premier_League.csv', index_col=0)
sorted_matrix

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# Plot the reordered heatmap
plt.figure(figsize=(12, 6))
sns.heatmap(sorted_matrix, annot=True, cmap="Blues", linewidths=0.5, cbar_kws={'label': 'Probability'})

# Understat

In [13]:
league_name="ENG-Premier League" 
previous_season='2025'
current_season='2026'
understat = sd.Understat(leagues=league_name, seasons=[previous_season, current_season])
matches = understat.read_schedule()
matches

[09/20/26 13:58:07] INFO     Saving cached data to /Users/jaakkotoivonen/soccerdata/data/Understat   ]8;id=864550;file:///Users/jaakkotoivonen/repos/soccerdata/soccerdata/_common.py\_common.py]8;;\:]8;id=502630;file:///Users/jaakkotoivonen/repos/soccerdata/soccerdata/_common.py#250\250]8;;\

KeyError: 'stat'

# Sofascore

In [8]:
league_name = 'ENG-Premier League'
current_season = '2026'
sofascore = sd.Sofascore(leagues=league_name, seasons=[current_season]) #no_cache=True
matches = sofascore.read_schedule()
matches

[09/20/26 13:09:46] INFO     Saving cached data to /Users/jaakkotoivonen/soccerdata/data/Sofascore   ]8;id=108042;file:///Users/jaakkotoivonen/repos/soccerdata/soccerdata/_common.py\_common.py]8;;\:]8;id=752310;file:///Users/jaakkotoivonen/repos/soccerdata/soccerdata/_common.py#250\250]8;;\

                                                                  round  week  \
league             season game
ENG-Premier League 2627   2026-08-21 Arsenal-Coventry City            1     1
                          2026-08-22 Brentford-Tottenham Hotspur      1     1
                          2026-08-22 Everton-Crystal Palace           1     1
                          2026-08-22 Hull City-Manchester United      1     1
                          2026-08-22 Ipswich Town-Sunderland          1     1
...                                                                 ...   ...
                          2027-05-30 Hull City-Newcastle United      38    38
                          2027-05-30 Ipswich Town-Everton            38    38
                          2027-05-30 Liverpool FC-Bournemouth        38    38
                          2027-05-30 Manchester United-Fulham        38    38
                          2027-05-30 Sunderland-Manchester City      38    38

                                                                                      date  \
league             season game
ENG-Premier League 2627   2026-08-21 Arsenal-Coventry City       2026-08-21 19:00:00+00:00
                          2026-08-22 Brentford-Tottenham Hotspur 2026-08-22 16:30:00+00:00
                          2026-08-22 Everton-Crystal Palace      2026-08-22 14:00:00+00:00
                          2026-08-22 Hull City-Manchester United 2026-08-22 11:30:00+00:00
                          2026-08-22 Ipswich Town-Sunderland     2026-08-22 14:00:00+00:00
...                                                                                    ...
                          2027-05-30 Hull City-Newcastle United  2027-05-30 15:00:00+00:00
                          2027-05-30 Ipswich Town-Everton        2027-05-30 15:00:00+00:00
                          2027-05-30 Liverpool FC-Bournemouth    2027-05-30 15:00:00+00:00
                          2027-05-30 Manchester United-Fulham    2027-05-30 15:00:00+00:00
                          2027-05-30 Sunderland-Manchester City  2027-05-30 15:00:00+00:00

                                                                          home_team  \
league             season game
ENG-Premier League 2627   2026-08-21 Arsenal-Coventry City                  Arsenal
                          2026-08-22 Brentford-Tottenham Hotspur          Brentford
                          2026-08-22 Everton-Crystal Palace                 Everton
                          2026-08-22 Hull City-Manchester United          Hull City
                          2026-08-22 Ipswich Town-Sunderland           Ipswich Town
...                                                                             ...
                          2027-05-30 Hull City-Newcastle United           Hull City
                          2027-05-30 Ipswich Town-Everton              Ipswich Town
                          2027-05-30 Liverpool FC-Bournemouth          Liverpool FC
                          2027-05-30 Manchester United-Fulham     Manchester United
                          2027-05-30 Sunderland-Manchester City          Sunderland

                                                                          away_team  \
league             season game
ENG-Premier League 2627   2026-08-21 Arsenal-Coventry City            Coventry City
                          2026-08-22 Brentford-Tottenham Hotspur  Tottenham Hotspur
                          2026-08-22 Everton-Crystal Palace          Crystal Palace
                          2026-08-22 Hull City-Manchester United  Manchester United
                          2026-08-22 Ipswich Town-Sunderland             Sunderland
...                                                                             ...
                          2027-05-30 Hull City-Newcastle United    Newcastle United
                          2027-05-30 Ipswich Town-Everton                   Everton
                          2027-05-30 Liverpool FC-Bournemouth           Bournemouth
                          2027-05-30 Manchester United-Fulham                Fulham
                          2027-05-30 Sunderland-Manchester City     Manchester City

                                                                  home_score  \
league             season game
ENG-Premier League 2627   2026-08-21 Arsenal-Coventry City               3.0
                          2026-08-22 Brentford-Tottenham Hotspur         3.0
                          2026-08-22 Everton-Crystal Palace              2.0
                          2026-08-22 Hull City-Manchester United         2.0
                          2026-08-22 Ipswich Town-Sunderland             2.0
...                                                                      ...
                          2027-05-30 Hull City-Newcastle United          NaN
                          2027-05-30 Ipswich Town-Everton                NaN
                          2027-05-30 Liverpool FC-Bournemouth            NaN
                          2027-05-30 Manchester United-Fulham            NaN
                          2027-05-30 Sunderland-Manchester City          NaN

                                                                  away_score  \
league             season game
ENG-Premier League 2627   2026-08-21 Arsenal-Coventry City               0.0
                          2026-08-22 Brentford-Tottenham Hotspur         0.0
                          2026-08-22 Everton-Crystal Palace              0.0
                          2026-08-22 Hull City-Manchester United         0.0
                          2026-08-22 Ipswich Town-Sunderland             1.0
...                                                                      ...
                          2027-05-30 Hull City-Newcastle United          NaN
                          2027-05-30 Ipswich Town-Everton                NaN
                          2027-05-30 Liverpool FC-Bournemouth            NaN
                          2027-05-30 Manchester United-Fulham            NaN
                          2027-05-30 Sunderland-Manchester City          NaN

                                                                   game_id
league             season game
ENG-Premier League 2627   2026-08-21 Arsenal-Coventry City        16363633
                          2026-08-22 Brentford-Tottenham Hotspur  16363242
                          2026-08-22 Everton-Crystal Palace       16363635
                          2026-08-22 Hull City-Manchester United  16363634
                          2026-08-22 Ipswich Town-Sunderland      16363636
...                                                                    ...
                          2027-05-30 Hull City-Newcastle United   16363241
                          2027-05-30 Ipswich Town-Everton         16363234
                          2027-05-30 Liverpool FC-Bournemouth     16363268
                          2027-05-30 Manchester United-Fulham     16363239
                          2027-05-30 Sunderland-Manchester City   16363240

[380 rows x 8 columns]

In [9]:
matches.tail(20)

                                                                          round  \
league             season game
ENG-Premier League 2627   2027-05-23 Bournemouth-Chelsea                     37
                          2027-05-23 Brentford-Hull City                     37
                          2027-05-23 Brighton & Hove Albion-Liverpool FC     37
                          2027-05-23 Everton-Arsenal                         37
                          2027-05-23 Fulham-Coventry City                    37
                          2027-05-23 Leeds United-Sunderland                 37
                          2027-05-23 Manchester City-Aston Villa             37
                          2027-05-23 Newcastle United-Crystal Palace         37
                          2027-05-23 Nottingham Forest-Ipswich Town          37
                          2027-05-23 Tottenham Hotspur-Manchester United     37
                          2027-05-30 Arsenal-Brighton & Hove Albion          38
                          2027-05-30 Aston Villa-Tottenham Hotspur           38
                          2027-05-30 Chelsea-Brentford                       38
                          2027-05-30 Coventry City-Nottingham Forest         38
                          2027-05-30 Crystal Palace-Leeds United             38
                          2027-05-30 Hull City-Newcastle United              38
                          2027-05-30 Ipswich Town-Everton                    38
                          2027-05-30 Liverpool FC-Bournemouth                38
                          2027-05-30 Manchester United-Fulham                38
                          2027-05-30 Sunderland-Manchester City              38

                                                                          week  \
league             season game
ENG-Premier League 2627   2027-05-23 Bournemouth-Chelsea                    37
                          2027-05-23 Brentford-Hull City                    37
                          2027-05-23 Brighton & Hove Albion-Liverpool FC    37
                          2027-05-23 Everton-Arsenal                        37
                          2027-05-23 Fulham-Coventry City                   37
                          2027-05-23 Leeds United-Sunderland                37
                          2027-05-23 Manchester City-Aston Villa            37
                          2027-05-23 Newcastle United-Crystal Palace        37
                          2027-05-23 Nottingham Forest-Ipswich Town         37
                          2027-05-23 Tottenham Hotspur-Manchester United    37
                          2027-05-30 Arsenal-Brighton & Hove Albion         38
                          2027-05-30 Aston Villa-Tottenham Hotspur          38
                          2027-05-30 Chelsea-Brentford                      38
                          2027-05-30 Coventry City-Nottingham Forest        38
                          2027-05-30 Crystal Palace-Leeds United            38
                          2027-05-30 Hull City-Newcastle United             38
                          2027-05-30 Ipswich Town-Everton                   38
                          2027-05-30 Liverpool FC-Bournemouth               38
                          2027-05-30 Manchester United-Fulham               38
                          2027-05-30 Sunderland-Manchester City             38

                                                                                              date  \
league             season game
ENG-Premier League 2627   2027-05-23 Bournemouth-Chelsea                 2027-05-23 14:00:00+00:00
                          2027-05-23 Brentford-Hull City                 2027-05-23 14:00:00+00:00
                          2027-05-23 Brighton & Hove Albion-Liverpool FC 2027-05-23 14:00:00+00:00
                          2027-05-23 Everton-Arsenal                     2027-05-23 14:00:00+00:00
                          2027-05-23 Fulham-Coventry City                2027-05-23 14:00:00+00:00
                          2027-05-23 Leeds United-Sunderland             2027-05-23 14:00:00+00:00
                          2027-05-23 Manchester City-Aston Villa         2027-05-23 14:00:00+00:00
                          2027-05-23 Newcastle United-Crystal Palace     2027-05-23 14:00:00+00:00
                          2027-05-23 Nottingham Forest-Ipswich Town      2027-05-23 14:00:00+00:00
                          2027-05-23 Tottenham Hotspur-Manchester United 2027-05-23 14:00:00+00:00
                          2027-05-30 Arsenal-Brighton & Hove Albion      2027-05-30 15:00:00+00:00
                          2027-05-30 Aston Villa-Tottenham Hotspur       2027-05-30 15:00:00+00:00
                          2027-05-30 Chelsea-Brentford                   2027-05-30 15:00:00+00:00
                          2027-05-30 Coventry City-Nottingham Forest     2027-05-30 15:00:00+00:00
                          2027-05-30 Crystal Palace-Leeds United         2027-05-30 15:00:00+00:00
                          2027-05-30 Hull City-Newcastle United          2027-05-30 15:00:00+00:00
                          2027-05-30 Ipswich Town-Everton                2027-05-30 15:00:00+00:00
                          2027-05-30 Liverpool FC-Bournemouth            2027-05-30 15:00:00+00:00
                          2027-05-30 Manchester United-Fulham            2027-05-30 15:00:00+00:00
                          2027-05-30 Sunderland-Manchester City          2027-05-30 15:00:00+00:00

                                                                                       home_team  \
league             season game
ENG-Premier League 2627   2027-05-23 Bournemouth-Chelsea                             Bournemouth
                          2027-05-23 Brentford-Hull City                               Brentford
                          2027-05-23 Brighton & Hove Albion-Liverpool FC  Brighton & Hove Albion
                          2027-05-23 Everton-Arsenal                                     Everton
                          2027-05-23 Fulham-Coventry City                                 Fulham
                          2027-05-23 Leeds United-Sunderland                        Leeds United
                          2027-05-23 Manchester City-Aston Villa                 Manchester City
                          2027-05-23 Newcastle United-Crystal Palace            Newcastle United
                          2027-05-23 Nottingham Forest-Ipswich Town            Nottingham Forest
                          2027-05-23 Tottenham Hotspur-Manchester United       Tottenham Hotspur
                          2027-05-30 Arsenal-Brighton & Hove Albion                      Arsenal
                          2027-05-30 Aston Villa-Tottenham Hotspur                   Aston Villa
                          2027-05-30 Chelsea-Brentford                                   Chelsea
                          2027-05-30 Coventry City-Nottingham Forest               Coventry City
                          2027-05-30 Crystal Palace-Leeds United                  Crystal Palace
                          2027-05-30 Hull City-Newcastle United                        Hull City
                          2027-05-30 Ipswich Town-Everton                           Ipswich Town
                          2027-05-30 Liverpool FC-Bournemouth                       Liverpool FC
                          2027-05-30 Manchester United-Fulham                  Manchester United
                          2027-05-30 Sunderland-Manchester City                       Sunderland

                                                                                       away_team  \
league             season game
ENG-Premier League 2627   2027-05-23 Bournemouth-Chelsea                                 Chelsea
                          2027-05-23 Brentford-Hull City                               Hull City
                          2027-05-23 Brighton & Hove Albion-Liverpool FC            Liverpool FC
                          2027-05-23 Everton-Arsenal                                     Arsenal
                          2027-05-23 Fulham-Coventry City                          Coventry City
                          2027-05-23 Leeds United-Sunderland                          Sunderland
                          2027-05-23 Manchester City-Aston Villa                     Aston Villa
                          2027-05-23 Newcastle United-Crystal Palace              Crystal Palace
                          2027-05-23 Nottingham Forest-Ipswich Town                 Ipswich Town
                          2027-05-23 Tottenham Hotspur-Manchester United       Manchester United
                          2027-05-30 Arsenal-Brighton & Hove Albion       Brighton & Hove Albion
                          2027-05-30 Aston Villa-Tottenham Hotspur             Tottenham Hotspur
                          2027-05-30 Chelsea-Brentford                                 Brentford
                          2027-05-30 Coventry City-Nottingham Forest           Nottingham Forest
                          2027-05-30 Crystal Palace-Leeds United                    Leeds United
                          2027-05-30 Hull City-Newcastle United                 Newcastle United
                          2027-05-30 Ipswich Town-Everton                                Everton
                          2027-05-30 Liverpool FC-Bournemouth                        Bournemouth
                          2027-05-30 Manchester United-Fulham                             Fulham
                          2027-05-30 Sunderland-Manchester City                  Manchester City

                                                                          home_score  \
league             season game
ENG-Premier League 2627   2027-05-23 Bournemouth-Chelsea                         NaN
                          2027-05-23 Brentford-Hull City                         NaN
                          2027-05-23 Brighton & Hove Albion-Liverpool FC         NaN
                          2027-05-23 Everton-Arsenal                             NaN
                          2027-05-23 Fulham-Coventry City                        NaN
                          2027-05-23 Leeds United-Sunderland                     NaN
                          2027-05-23 Manchester City-Aston Villa                 NaN
                          2027-05-23 Newcastle United-Crystal Palace             NaN
                          2027-05-23 Nottingham Forest-Ipswich Town              NaN
                          2027-05-23 Tottenham Hotspur-Manchester United         NaN
                          2027-05-30 Arsenal-Brighton & Hove Albion              NaN
                          2027-05-30 Aston Villa-Tottenham Hotspur               NaN
                          2027-05-30 Chelsea-Brentford                           NaN
                          2027-05-30 Coventry City-Nottingham Forest             NaN
                          2027-05-30 Crystal Palace-Leeds United                 NaN
                          2027-05-30 Hull City-Newcastle United                  NaN
                          2027-05-30 Ipswich Town-Everton                        NaN
                          2027-05-30 Liverpool FC-Bournemouth                    NaN
                          2027-05-30 Manchester United-Fulham                    NaN
                          2027-05-30 Sunderland-Manchester City                  NaN

                                                                          away_score  \
league             season game
ENG-Premier League 2627   2027-05-23 Bournemouth-Chelsea                         NaN
                          2027-05-23 Brentford-Hull City                         NaN
                          2027-05-23 Brighton & Hove Albion-Liverpool FC         NaN
                          2027-05-23 Everton-Arsenal                             NaN
                          2027-05-23 Fulham-Coventry City                        NaN
                          2027-05-23 Leeds United-Sunderland                     NaN
                          2027-05-23 Manchester City-Aston Villa                 NaN
                          2027-05-23 Newcastle United-Crystal Palace             NaN
                          2027-05-23 Nottingham Forest-Ipswich Town              NaN
                          2027-05-23 Tottenham Hotspur-Manchester United         NaN
                          2027-05-30 Arsenal-Brighton & Hove Albion              NaN
                          2027-05-30 Aston Villa-Tottenham Hotspur               NaN
                          2027-05-30 Chelsea-Brentford                           NaN
                          2027-05-30 Coventry City-Nottingham Forest             NaN
                          2027-05-30 Crystal Palace-Leeds United                 NaN
                          2027-05-30 Hull City-Newcastle United                  NaN
                          2027-05-30 Ipswich Town-Everton                        NaN
                          2027-05-30 Liverpool FC-Bournemouth                    NaN
                          2027-05-30 Manchester United-Fulham                    NaN
                          2027-05-30 Sunderland-Manchester City                  NaN

                                                                           game_id
league             season game
ENG-Premier League 2627   2027-05-23 Bournemouth-Chelsea                  16363224
                          2027-05-23 Brentford-Hull City                  16363222
                          2027-05-23 Brighton & Hove Albion-Liverpool FC  16363227
                          2027-05-23 Everton-Arsenal                      16363225
                          2027-05-23 Fulham-Coventry City                 16363226
                          2027-05-23 Leeds United-Sunderland              16363230
                          2027-05-23 Manchester City-Aston Villa          16363267
                          2027-05-23 Newcastle United-Crystal Palace      16363231
                          2027-05-23 Nottingham Forest-Ipswich Town       16363228
                          2027-05-23 Tottenham Hotspur-Manchester United  16363229
                          2027-05-30 Arsenal-Brighton & Hove Albion       16363232
                          2027-05-30 Aston Villa-Tottenham Hotspur        16363237
                          2027-05-30 Chelsea-Brentford                    16363233
                          2027-05-30 Coventry City-Nottingham Forest      16363265
                          2027-05-30 Crystal Palace-Leeds United          16363235
                          2027-05-30 Hull City-Newcastle United           16363241
                          2027-05-30 Ipswich Town-Everton                 16363234
                          2027-05-30 Liverpool FC-Bournemouth             16363268
                          2027-05-30 Manchester United-Fulham             16363239
                          2027-05-30 Sunderland-Manchester City           16363240

In [10]:
matches[matches.home_score.notnull()].tail(20)

                                                                           round  \
league             season game
ENG-Premier League 2627   2026-09-05 Newcastle United-Bournemouth              3
                          2026-09-05 Nottingham Forest-Tottenham Hotspur       3
                          2026-09-06 Arsenal-Chelsea                           3
                          2026-09-06 Everton-Manchester United                 3
                          2026-09-12 Aston Villa-Nottingham Forest             4
                          2026-09-12 Bournemouth-Brentford                     4
                          2026-09-12 Chelsea-Hull City                         4
                          2026-09-12 Crystal Palace-Ipswich Town               4
                          2026-09-12 Liverpool FC-Fulham                       4
                          2026-09-12 Sunderland-Arsenal                        4
                          2026-09-12 Tottenham Hotspur-Everton                 4
                          2026-09-13 Coventry City-Brighton & Hove Albion      4
                          2026-09-13 Manchester United-Manchester City         4
                          2026-09-14 Leeds United-Newcastle United             4
                          2026-09-18 Brentford-Chelsea                         5
                          2026-09-19 Brighton & Hove Albion-Arsenal            5
                          2026-09-19 Everton-Ipswich Town                      5
                          2026-09-19 Newcastle United-Hull City                5
                          2026-09-19 Nottingham Forest-Coventry City           5
                          2026-09-19 Tottenham Hotspur-Aston Villa             5

                                                                           week  \
league             season game
ENG-Premier League 2627   2026-09-05 Newcastle United-Bournemouth             3
                          2026-09-05 Nottingham Forest-Tottenham Hotspur      3
                          2026-09-06 Arsenal-Chelsea                          3
                          2026-09-06 Everton-Manchester United                3
                          2026-09-12 Aston Villa-Nottingham Forest            4
                          2026-09-12 Bournemouth-Brentford                    4
                          2026-09-12 Chelsea-Hull City                        4
                          2026-09-12 Crystal Palace-Ipswich Town              4
                          2026-09-12 Liverpool FC-Fulham                      4
                          2026-09-12 Sunderland-Arsenal                       4
                          2026-09-12 Tottenham Hotspur-Everton                4
                          2026-09-13 Coventry City-Brighton & Hove Albion     4
                          2026-09-13 Manchester United-Manchester City        4
                          2026-09-14 Leeds United-Newcastle United            4
                          2026-09-18 Brentford-Chelsea                        5
                          2026-09-19 Brighton & Hove Albion-Arsenal           5
                          2026-09-19 Everton-Ipswich Town                     5
                          2026-09-19 Newcastle United-Hull City               5
                          2026-09-19 Nottingham Forest-Coventry City          5
                          2026-09-19 Tottenham Hotspur-Aston Villa            5

                                                                                               date  \
league             season game
ENG-Premier League 2627   2026-09-05 Newcastle United-Bournemouth         2026-09-05 11:30:00+00:00
                          2026-09-05 Nottingham Forest-Tottenham Hotspur  2026-09-05 14:00:00+00:00
                          2026-09-06 Arsenal-Chelsea                      2026-09-06 15:30:00+00:00
                          2026-09-06 Everton-Manchester United            2026-09-06 13:00:00+00:00
                          2026-09-12 Aston Villa-Nottingham Forest        2026-09-12 14:00:00+00:00
                          2026-09-12 Bournemouth-Brentford                2026-09-12 14:00:00+00:00
                          2026-09-12 Chelsea-Hull City                    2026-09-12 14:00:00+00:00
                          2026-09-12 Crystal Palace-Ipswich Town          2026-09-12 14:00:00+00:00
                          2026-09-12 Liverpool FC-Fulham                  2026-09-12 14:00:00+00:00
                          2026-09-12 Sunderland-Arsenal                   2026-09-12 19:00:00+00:00
                          2026-09-12 Tottenham Hotspur-Everton            2026-09-12 16:30:00+00:00
                          2026-09-13 Coventry City-Brighton & Hove Albion 2026-09-13 13:00:00+00:00
                          2026-09-13 Manchester United-Manchester City    2026-09-13 15:30:00+00:00
                          2026-09-14 Leeds United-Newcastle United        2026-09-14 19:00:00+00:00
                          2026-09-18 Brentford-Chelsea                    2026-09-18 19:00:00+00:00
                          2026-09-19 Brighton & Hove Albion-Arsenal       2026-09-19 14:00:00+00:00
                          2026-09-19 Everton-Ipswich Town                 2026-09-19 14:00:00+00:00
                          2026-09-19 Newcastle United-Hull City           2026-09-19 14:00:00+00:00
                          2026-09-19 Nottingham Forest-Coventry City      2026-09-19 16:30:00+00:00
                          2026-09-19 Tottenham Hotspur-Aston Villa        2026-09-19 11:30:00+00:00

                                                                                        home_team  \
league             season game
ENG-Premier League 2627   2026-09-05 Newcastle United-Bournemouth                Newcastle United
                          2026-09-05 Nottingham Forest-Tottenham Hotspur        Nottingham Forest
                          2026-09-06 Arsenal-Chelsea                                      Arsenal
                          2026-09-06 Everton-Manchester United                            Everton
                          2026-09-12 Aston Villa-Nottingham Forest                    Aston Villa
                          2026-09-12 Bournemouth-Brentford                            Bournemouth
                          2026-09-12 Chelsea-Hull City                                    Chelsea
                          2026-09-12 Crystal Palace-Ipswich Town                   Crystal Palace
                          2026-09-12 Liverpool FC-Fulham                             Liverpool FC
                          2026-09-12 Sunderland-Arsenal                                Sunderland
                          2026-09-12 Tottenham Hotspur-Everton                  Tottenham Hotspur
                          2026-09-13 Coventry City-Brighton & Hove Albion           Coventry City
                          2026-09-13 Manchester United-Manchester City          Manchester United
                          2026-09-14 Leeds United-Newcastle United                   Leeds United
                          2026-09-18 Brentford-Chelsea                                  Brentford
                          2026-09-19 Brighton & Hove Albion-Arsenal        Brighton & Hove Albion
                          2026-09-19 Everton-Ipswich Town                                 Everton
                          2026-09-19 Newcastle United-Hull City                  Newcastle United
                          2026-09-19 Nottingham Forest-Coventry City            Nottingham Forest
                          2026-09-19 Tottenham Hotspur-Aston Villa              Tottenham Hotspur

                                                                                        away_team  \
league             season game
ENG-Premier League 2627   2026-09-05 Newcastle United-Bournemouth                     Bournemouth
                          2026-09-05 Nottingham Forest-Tottenham Hotspur        Tottenham Hotspur
                          2026-09-06 Arsenal-Chelsea                                      Chelsea
                          2026-09-06 Everton-Manchester United                  Manchester United
                          2026-09-12 Aston Villa-Nottingham Forest              Nottingham Forest
                          2026-09-12 Bournemouth-Brentford                              Brentford
                          2026-09-12 Chelsea-Hull City                                  Hull City
                          2026-09-12 Crystal Palace-Ipswich Town                     Ipswich Town
                          2026-09-12 Liverpool FC-Fulham                                   Fulham
                          2026-09-12 Sunderland-Arsenal                                   Arsenal
                          2026-09-12 Tottenham Hotspur-Everton                            Everton
                          2026-09-13 Coventry City-Brighton & Hove Albion  Brighton & Hove Albion
                          2026-09-13 Manchester United-Manchester City            Manchester City
                          2026-09-14 Leeds United-Newcastle United               Newcastle United
                          2026-09-18 Brentford-Chelsea                                    Chelsea
                          2026-09-19 Brighton & Hove Albion-Arsenal                       Arsenal
                          2026-09-19 Everton-Ipswich Town                            Ipswich Town
                          2026-09-19 Newcastle United-Hull City                         Hull City
                          2026-09-19 Nottingham Forest-Coventry City                Coventry City
                          2026-09-19 Tottenham Hotspur-Aston Villa                    Aston Villa

                                                                           home_score  \
league             season game
ENG-Premier League 2627   2026-09-05 Newcastle United-Bournemouth                 2.0
                          2026-09-05 Nottingham Forest-Tottenham Hotspur          0.0
                          2026-09-06 Arsenal-Chelsea                              2.0
                          2026-09-06 Everton-Manchester United                    2.0
                          2026-09-12 Aston Villa-Nottingham Forest                1.0
                          2026-09-12 Bournemouth-Brentford                        2.0
                          2026-09-12 Chelsea-Hull City                            2.0
                          2026-09-12 Crystal Palace-Ipswich Town                  2.0
                          2026-09-12 Liverpool FC-Fulham                          0.0
                          2026-09-12 Sunderland-Arsenal                           0.0
                          2026-09-12 Tottenham Hotspur-Everton                    0.0
                          2026-09-13 Coventry City-Brighton & Hove Albion         0.0
                          2026-09-13 Manchester United-Manchester City            0.0
                          2026-09-14 Leeds United-Newcastle United                4.0
                          2026-09-18 Brentford-Chelsea                            3.0
                          2026-09-19 Brighton & Hove Albion-Arsenal               3.0
                          2026-09-19 Everton-Ipswich Town                         1.0
                          2026-09-19 Newcastle United-Hull City                   2.0
                          2026-09-19 Nottingham Forest-Coventry City              0.0
                          2026-09-19 Tottenham Hotspur-Aston Villa                2.0

                                                                           away_score  \
league             season game
ENG-Premier League 2627   2026-09-05 Newcastle United-Bournemouth                 2.0
                          2026-09-05 Nottingham Forest-Tottenham Hotspur          0.0
                          2026-09-06 Arsenal-Chelsea                              1.0
                          2026-09-06 Everton-Manchester United                    2.0
                          2026-09-12 Aston Villa-Nottingham Forest                2.0
                          2026-09-12 Bournemouth-Brentford                        2.0
                          2026-09-12 Chelsea-Hull City                            2.0
                          2026-09-12 Crystal Palace-Ipswich Town                  3.0
                          2026-09-12 Liverpool FC-Fulham                          0.0
                          2026-09-12 Sunderland-Arsenal                           2.0
                          2026-09-12 Tottenham Hotspur-Everton                    0.0
                          2026-09-13 Coventry City-Brighton & Hove Albion         5.0
                          2026-09-13 Manchester United-Manchester City            1.0
                          2026-09-14 Leeds United-Newcastle United                1.0
                          2026-09-18 Brentford-Chelsea                            0.0
                          2026-09-19 Brighton & Hove Albion-Arsenal               0.0
                          2026-09-19 Everton-Ipswich Town                         0.0
                          2026-09-19 Newcastle United-Hull City                   1.0
                          2026-09-19 Nottingham Forest-Coventry City              1.0
                          2026-09-19 Tottenham Hotspur-Aston Villa                3.0

                                                                            game_id
league             season game
ENG-Premier League 2627   2026-09-05 Newcastle United-Bournemouth          16363637
                          2026-09-05 Nottingham Forest-Tottenham Hotspur   16363638
                          2026-09-06 Arsenal-Chelsea                       16363257
                          2026-09-06 Everton-Manchester United             16363259
                          2026-09-12 Aston Villa-Nottingham Forest         16363639
                          2026-09-12 Bournemouth-Brentford                 16363640
                          2026-09-12 Chelsea-Hull City                     16363641
                          2026-09-12 Crystal Palace-Ipswich Town           16363643
                          2026-09-12 Liverpool FC-Fulham                   16363264
                          2026-09-12 Sunderland-Arsenal                    16363646
                          2026-09-12 Tottenham Hotspur-Everton             16363647
                          2026-09-13 Coventry City-Brighton & Hove Albion  16363642
                          2026-09-13 Manchester United-Manchester City     16363645
                          2026-09-14 Leeds United-Newcastle United         16363644
                          2026-09-18 Brentford-Chelsea                     16363649
                          2026-09-19 Brighton & Hove Albion-Arsenal        16363650
                          2026-09-19 Everton-Ipswich Town                  16363651
                          2026-09-19 Newcastle United-Hull City            16363868
                          2026-09-19 Nottingham Forest-Coventry City       16363869
                          2026-09-19 Tottenham Hotspur-Aston Villa         16363870

In [5]:
sofascore.read_leagues()

                    league_id region
league
ENG-Premier League         17    ENG

# MatchHistory

In [11]:
league_name = 'ENG-Premier League'
current_season = '2026'
match_history = sd.MatchHistory(leagues=league_name, seasons=[2026])
matches = match_history.read_games()
matches

[09/20/26 13:14:30] INFO     Saving cached data to                                                   ]8;id=62153;file:///Users/jaakkotoivonen/repos/soccerdata/soccerdata/_common.py\_common.py]8;;\:]8;id=262410;file:///Users/jaakkotoivonen/repos/soccerdata/soccerdata/_common.py#250\250]8;;\
                             /Users/jaakkotoivonen/soccerdata/data/MatchHistory

[09/20/26 13:14:31] INFO     Parsing league=E0 season=2627                                      ]8;id=394287;file:///Users/jaakkotoivonen/repos/soccerdata/soccerdata/match_history.py\match_history.py]8;;\:]8;id=597067;file:///Users/jaakkotoivonen/repos/soccerdata/soccerdata/match_history.py#28\28]8;;\

                                                                              date  \
league             season game
ENG-Premier League 2627   2026-08-21 Arsenal-Coventry          2026-08-21 20:00:00
                          2026-08-22 Brentford-Tottenham       2026-08-22 17:30:00
                          2026-08-22 Everton-Crystal Palace    2026-08-22 15:00:00
                          2026-08-22 Hull-Man United           2026-08-22 12:30:00
                          2026-08-22 Ipswich-Sunderland        2026-08-22 15:00:00
                          2026-08-22 Nott'm Forest-Leeds       2026-08-22 15:00:00
                          2026-08-23 Brighton-Aston Villa      2026-08-23 14:00:00
                          2026-08-23 Man City-Bournemouth      2026-08-23 14:00:00
                          2026-08-23 Newcastle-Liverpool       2026-08-23 16:30:00
                          2026-08-24 Fulham-Chelsea            2026-08-24 20:00:00
                          2026-08-28 Crystal Palace-Man City   2026-08-28 20:00:00
                          2026-08-29 Bournemouth-Everton       2026-08-29 15:00:00
                          2026-08-29 Coventry-Hull             2026-08-29 15:00:00
                          2026-08-29 Liverpool-Nott'm Forest   2026-08-29 12:30:00
                          2026-08-29 Tottenham-Newcastle       2026-08-29 17:30:00
                          2026-08-30 Chelsea-Brighton          2026-08-30 14:00:00
                          2026-08-30 Leeds-Brentford           2026-08-30 14:00:00
                          2026-08-30 Man United-Ipswich        2026-08-30 16:30:00
                          2026-08-30 Sunderland-Fulham         2026-08-30 14:00:00
                          2026-08-31 Aston Villa-Arsenal       2026-08-31 20:00:00
                          2026-09-04 Ipswich-Liverpool         2026-09-04 20:00:00
                          2026-09-05 Brentford-Sunderland      2026-09-05 15:00:00
                          2026-09-05 Brighton-Leeds            2026-09-05 15:00:00
                          2026-09-05 Fulham-Crystal Palace     2026-09-05 15:00:00
                          2026-09-05 Hull-Aston Villa          2026-09-05 17:30:00
                          2026-09-05 Man City-Coventry         2026-09-05 15:00:00
                          2026-09-05 Newcastle-Bournemouth     2026-09-05 12:30:00
                          2026-09-05 Nott'm Forest-Tottenham   2026-09-05 15:00:00
                          2026-09-06 Arsenal-Chelsea           2026-09-06 16:30:00
                          2026-09-06 Everton-Man United        2026-09-06 14:00:00
                          2026-09-12 Aston Villa-Nott'm Forest 2026-09-12 15:00:00
                          2026-09-12 Bournemouth-Brentford     2026-09-12 15:00:00
                          2026-09-12 Chelsea-Hull              2026-09-12 15:00:00
                          2026-09-12 Crystal Palace-Ipswich    2026-09-12 15:00:00
                          2026-09-12 Liverpool-Fulham          2026-09-12 15:00:00
                          2026-09-12 Sunderland-Arsenal        2026-09-12 20:00:00
                          2026-09-12 Tottenham-Everton         2026-09-12 17:30:00
                          2026-09-13 Coventry-Brighton         2026-09-13 14:00:00
                          2026-09-13 Man United-Man City       2026-09-13 16:30:00
                          2026-09-14 Leeds-Newcastle           2026-09-14 20:00:00

                                                                     home_team  \
league             season game
ENG-Premier League 2627   2026-08-21 Arsenal-Coventry                  Arsenal
                          2026-08-22 Brentford-Tottenham             Brentford
                          2026-08-22 Everton-Crystal Palace            Everton
                          2026-08-22 Hull-Man United                      Hull
                          2026-08-22 Ipswich-Sunderland                Ipswich
                          2026-08-22 Nott'm Forest-Leeds         Nott'm Forest
                          2026-08-23 Brighton-Aston Villa             Brighton
                          2026-08-23 Man City-Bournemouth             Man City
                          2026-08-23 Newcastle-Liverpool             Newcastle
                          2026-08-24 Fulham-Chelsea                     Fulham
                          2026-08-28 Crystal Palace-Man City    Crystal Palace
                          2026-08-29 Bournemouth-Everton           Bournemouth
                          2026-08-29 Coventry-Hull                    Coventry
                          2026-08-29 Liverpool-Nott'm Forest         Liverpool
                          2026-08-29 Tottenham-Newcastle             Tottenham
                          2026-08-30 Chelsea-Brighton                  Chelsea
                          2026-08-30 Leeds-Brentford                     Leeds
                          2026-08-30 Man United-Ipswich             Man United
                          2026-08-30 Sunderland-Fulham              Sunderland
                          2026-08-31 Aston Villa-Arsenal           Aston Villa
                          2026-09-04 Ipswich-Liverpool                 Ipswich
                          2026-09-05 Brentford-Sunderland            Brentford
                          2026-09-05 Brighton-Leeds                   Brighton
                          2026-09-05 Fulham-Crystal Palace              Fulham
                          2026-09-05 Hull-Aston Villa                     Hull
                          2026-09-05 Man City-Coventry                Man City
                          2026-09-05 Newcastle-Bournemouth           Newcastle
                          2026-09-05 Nott'm Forest-Tottenham     Nott'm Forest
                          2026-09-06 Arsenal-Chelsea                   Arsenal
                          2026-09-06 Everton-Man United                Everton
                          2026-09-12 Aston Villa-Nott'm Forest     Aston Villa
                          2026-09-12 Bournemouth-Brentford         Bournemouth
                          2026-09-12 Chelsea-Hull                      Chelsea
                          2026-09-12 Crystal Palace-Ipswich     Crystal Palace
                          2026-09-12 Liverpool-Fulham                Liverpool
                          2026-09-12 Sunderland-Arsenal             Sunderland
                          2026-09-12 Tottenham-Everton               Tottenham
                          2026-09-13 Coventry-Brighton                Coventry
                          2026-09-13 Man United-Man City            Man United
                          2026-09-14 Leeds-Newcastle                     Leeds

                                                                     away_team  \
league             season game
ENG-Premier League 2627   2026-08-21 Arsenal-Coventry                 Coventry
                          2026-08-22 Brentford-Tottenham             Tottenham
                          2026-08-22 Everton-Crystal Palace     Crystal Palace
                          2026-08-22 Hull-Man United                Man United
                          2026-08-22 Ipswich-Sunderland             Sunderland
                          2026-08-22 Nott'm Forest-Leeds                 Leeds
                          2026-08-23 Brighton-Aston Villa          Aston Villa
                          2026-08-23 Man City-Bournemouth          Bournemouth
                          2026-08-23 Newcastle-Liverpool             Liverpool
                          2026-08-24 Fulham-Chelsea                    Chelsea
                          2026-08-28 Crystal Palace-Man City          Man City
                          2026-08-29 Bournemouth-Everton               Everton
                          2026-08-29 Coventry-Hull                        Hull
                          2026-08-29 Liverpool-Nott'm Forest     Nott'm Forest
                          2026-08-29 Tottenham-Newcastle             Newcastle
                          2026-08-30 Chelsea-Brighton                 Brighton
                          2026-08-30 Leeds-Brentford                 Brentford
                          2026-08-30 Man United-Ipswich                Ipswich
                          2026-08-30 Sunderland-Fulham                  Fulham
                          2026-08-31 Aston Villa-Arsenal               Arsenal
                          2026-09-04 Ipswich-Liverpool               Liverpool
                          2026-09-05 Brentford-Sunderland           Sunderland
                          2026-09-05 Brighton-Leeds                      Leeds
                          2026-09-05 Fulham-Crystal Palace      Crystal Palace
                          2026-09-05 Hull-Aston Villa              Aston Villa
                          2026-09-05 Man City-Coventry                Coventry
                          2026-09-05 Newcastle-Bournemouth         Bournemouth
                          2026-09-05 Nott'm Forest-Tottenham         Tottenham
                          2026-09-06 Arsenal-Chelsea                   Chelsea
                          2026-09-06 Everton-Man United             Man United
                          2026-09-12 Aston Villa-Nott'm Forest   Nott'm Forest
                          2026-09-12 Bournemouth-Brentford           Brentford
                          2026-09-12 Chelsea-Hull                         Hull
                          2026-09-12 Crystal Palace-Ipswich            Ipswich
                          2026-09-12 Liverpool-Fulham                   Fulham
                          2026-09-12 Sunderland-Arsenal                Arsenal
                          2026-09-12 Tottenham-Everton                 Everton
                          2026-09-13 Coventry-Brighton                Brighton
                          2026-09-13 Man United-Man City              Man City
                          2026-09-14 Leeds-Newcastle                 Newcastle

                                                                FTHG  FTAG  \
league             season game
ENG-Premier League 2627   2026-08-21 Arsenal-Coventry              3     0
                          2026-08-22 Brentford-Tottenham           3     0
                          2026-08-22 Everton-Crystal Palace        2     0
                          2026-08-22 Hull-Man United               2     0
                          2026-08-22 Ipswich-Sunderland            2     1
                          2026-08-22 Nott'm Forest-Leeds           0     1
                          2026-08-23 Brighton-Aston Villa          4     0
                          2026-08-23 Man City-Bournemouth          2     1
                          2026-08-23 Newcastle-Liverpool           2     2
                          2026-08-24 Fulham-Chelsea                2     3
                          2026-08-28 Crystal Palace-Man City       1     4
                          2026-08-29 Bournemouth-Everton           1     1
                          2026-08-29 Coventry-Hull                 0     1
                          2026-08-29 Liverpool-Nott'm Forest       2     2
                          2026-08-29 Tottenham-Newcastle           0     2
                          2026-08-30 Chelsea-Brighton              4     3
                          2026-08-30 Leeds-Brentford               1     1
                          2026-08-30 Man United-Ipswich            5     2
                          2026-08-30 Sunderland-Fulham             1     0
                          2026-08-31 Aston Villa-Arsenal           0     1
                          2026-09-04 Ipswich-Liverpool             0     2
                          2026-09-05 Brentford-Sunderland          1     1
                          2026-09-05 Brighton-Leeds                1     1
                          2026-09-05 Fulham-Crystal Palace         2     3
                          2026-09-05 Hull-Aston Villa              0     0
                          2026-09-05 Man City-Coventry             1     0
                          2026-09-05 Newcastle-Bournemouth         2     2
                          2026-09-05 Nott'm Forest-Tottenham       0     0
                          2026-09-06 Arsenal-Chelsea               2     1
                          2026-09-06 Everton-Man United            2     2
                          2026-09-12 Aston Villa-Nott'm Forest     1     2
                          2026-09-12 Bournemouth-Brentford         2     2
                          2026-09-12 Chelsea-Hull                  2     2
                          2026-09-12 Crystal Palace-Ipswich        2     3
                          2026-09-12 Liverpool-Fulham              0     0
                          2026-09-12 Sunderland-Arsenal            0     2
                          2026-09-12 Tottenham-Everton             0     0
                          2026-09-13 Coventry-Brighton             0     5
                          2026-09-13 Man United-Man City           0     1
                          2026-09-14 Leeds-Newcastle               4     1

                                                               FTR  HTHG  \
league             season game
ENG-Premier League 2627   2026-08-21 Arsenal-Coventry            H     2
                          2026-08-22 Brentford-Tottenham         H     2
                          2026-08-22 Everton-Crystal Palace      H     1
                          2026-08-22 Hull-Man United             H     2
                          2026-08-22 Ipswich-Sunderland          H     1
                          2026-08-22 Nott'm Forest-Leeds         A     0
                          2026-08-23 Brighton-Aston Villa        H     4
                          2026-08-23 Man City-Bournemouth        H     0
                          2026-08-23 Newcastle-Liverpool         D     1
                          2026-08-24 Fulham-Chelsea              A     1
                          2026-08-28 Crystal Palace-Man City     A     0
                          2026-08-29 Bournemouth-Everton         D     1
                          2026-08-29 Coventry-Hull               A     0
                          2026-08-29 Liverpool-Nott'm Forest     D     0
                          2026-08-29 Tottenham-Newcastle         A     0
                          2026-08-30 Chelsea-Brighton            H     3
                          2026-08-30 Leeds-Brentford             D     0
                          2026-08-30 Man United-Ipswich          H     1
                          2026-08-30 Sunderland-Fulham           H     0
                          2026-08-31 Aston Villa-Arsenal         A     0
                          2026-09-04 Ipswich-Liverpool           A     0
                          2026-09-05 Brentford-Sunderland        D     0
                          2026-09-05 Brighton-Leeds              D     0
                          2026-09-05 Fulham-Crystal Palace       A     2
                          2026-09-05 Hull-Aston Villa            D     0
                          2026-09-05 Man City-Coventry           H     1
                          2026-09-05 Newcastle-Bournemouth       D     1
                          2026-09-05 Nott'm Forest-Tottenham     D     0
                          2026-09-06 Arsenal-Chelsea             H     1
                          2026-09-06 Everton-Man United          D     0
                          2026-09-12 Aston Villa-Nott'm Forest   A     0
                          2026-09-12 Bournemouth-Brentford       D     1
                          2026-09-12 Chelsea-Hull                D     1
                          2026-09-12 Crystal Palace-Ipswich      A     1
                          2026-09-12 Liverpool-Fulham            D     0
                          2026-09-12 Sunderland-Arsenal          A     0
                          2026-09-12 Tottenham-Everton           D     0
                          2026-09-13 Coventry-Brighton           A     0
                          2026-09-13 Man United-Man City         A     0
                          2026-09-14 Leeds-Newcastle             H     3

                                                                HTAG HTR  \
league             season game
ENG-Premier League 2627   2026-08-21 Arsenal-Coventry              0   H
                          2026-08-22 Brentford-Tottenham           0   H
                          2026-08-22 Everton-Crystal Palace        0   H
                          2026-08-22 Hull-Man United               0   H
                          2026-08-22 Ipswich-Sunderland            1   D
                          2026-08-22 Nott'm Forest-Leeds           0   D
                          2026-08-23 Brighton-Aston Villa          0   H
                          2026-08-23 Man City-Bournemouth          1   A
                          2026-08-23 Newcastle-Liverpool           0   H
                          2026-08-24 Fulham-Chelsea                2   A
                          2026-08-28 Crystal Palace-Man City       1   A
                          2026-08-29 Bournemouth-Everton           0   H
                          2026-08-29 Coventry-Hull                 0   D
                          2026-08-29 Liverpool-Nott'm Forest       1   A
                          2026-08-29 Tottenham-Newcastle           0   D
                          2026-08-30 Chelsea-Brighton              1   H
                          2026-08-30 Leeds-Brentford               1   A
                          2026-08-30 Man United-Ipswich            1   D
                          2026-08-30 Sunderland-Fulham             0   D
                          2026-08-31 Aston Villa-Arsenal           0   D
                          2026-09-04 Ipswich-Liverpool             2   A
                          2026-09-05 Brentford-Sunderland          0   D
                          2026-09-05 Brighton-Leeds                1   A
                          2026-09-05 Fulham-Crystal Palace         1   H
                          2026-09-05 Hull-Aston Villa              0   D
                          2026-09-05 Man City-Coventry             0   H
                          2026-09-05 Newcastle-Bournemouth         2   A
                          2026-09-05 Nott'm Forest-Tottenham       0   D
                          2026-09-06 Arsenal-Chelsea               1   D
                          2026-09-06 Everton-Man United            0   D
                          2026-09-12 Aston Villa-Nott'm Forest     0   D
                          2026-09-12 Bournemouth-Brentford         1   D
                          2026-09-12 Chelsea-Hull                  2   A
                          2026-09-12 Crystal Palace-Ipswich        2   A
                          2026-09-12 Liverpool-Fulham              0   D
                          2026-09-12 Sunderland-Arsenal            0   D
                          2026-09-12 Tottenham-Everton             0   D
                          2026-09-13 Coventry-Brighton             1   A
                          2026-09-13 Man United-Man City           0   D
                          2026-09-14 Leeds-Newcastle               0   H

                                                                     referee  \
league             season game
ENG-Premier League 2627   2026-08-21 Arsenal-Coventry              T Bramall
                          2026-08-22 Brentford-Tottenham            M Oliver
                          2026-08-22 Everton-Crystal Palace        P Tierney
                          2026-08-22 Hull-Man United               D England
                          2026-08-22 Ipswich-Sunderland             F Hallam
                          2026-08-22 Nott'm Forest-Leeds             R Jones
                          2026-08-23 Brighton-Aston Villa           P Bankes
                          2026-08-23 Man City-Bournemouth          J Gillett
                          2026-08-23 Newcastle-Liverpool           S Attwell

In [ ]:
match_history.available_leagues()

# Club Elo

In [ ]:
club_elo = sd.ClubElo()
scores = club_elo.read_by_date()
scores